FROM rustlang/rust:nightly-slim

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN gcc -g -o tests/fixtures/bin/test_simple tests/fixtures/test_simple.c

CMD ["cargo", "test"]
